### ISSUE TITLE
Node point counts

### ISSUE THREAD

**Issue by connormanning** [hobu/untwine#10]
Seeing two issues with the number of points in the output.

- Zero-point nodes can appear in the output
- The distribution of point count per node is non-uniform

Some nodes are very small: ignoring the zero-point nodes mentioned, nodes of only 100-500 points are very common.  But there are also nodes of almost 2 million points.  In particular I'm using the SNCF set but I'd imagine this would be more prominent on dense drone data (will try that next).

For comparison:

- [Entwine](https://gist.github.com/connormanning/d013b2774a64f8f7b21c61df15373f94) - a soft target of 65k points/node.  Particularly toward the top levels there may be some poorly distributed small nodes, but in general there's uniformity within a factor of 2 or so.
- [Untwine](https://gist.github.com/connormanning/0dafe6ded892e9b9e2b2ca28c2767dda)

I'm not sure of a mechanism with the current sampling method to make things more uniform and I believe there's currently some work in progress on this, but I figured we could use this issue to track the progress of the sampling distributions as that stuff is developed.

**Comment by abellgithub** [comment]
You should try again with the latest changes that were pushed this afternoon. You'll still see some large nodes, but it's much better. The end-node size also depends on a guess on uniformity, which may be wrong.

If you can figure out *why* the current sampling scheme is significantly different from what you get with entwine, that would be great, though I think an adjustment to make the sampling grid smaller would certainly help as well. If you are aiming for spacing at some rate, there's only so much that you can do when the PC is not uniform.

**Comment by abellgithub** [comment]
Closing until there are more actionable complaints.
