### ISSUE TITLE
Hardcoded span in ept.json

### ISSUE THREAD

**Issue by wonder-sk** [hobu/untwine#11]
`bu` currently always writes `span` = 128 in ept.json - I believe it should be estimated based on the expected density of data at various depths of the octree.

This information is quite important for renderer to determine whether a particular octree node gives enough detail or whether its children should be loaded as well. For example, if a node's cubic bounding box would be 1024 meters (in map coordinates), then with span of 128 we estimate error of the node to be 1024 / 128 = 8 meters. When deciding whether a node has enough detail, we take into account camera position in the 3D scene, the node's error (in map coordinates) and calculate approximate node's error in screen coordinates - which is then compared to the max allowed error (in screen coordinates) specified by the user (e.g. 1 pixel). So, with hardcoded `span` there is a risk that we would be switching to child nodes either too early or too late.

**Comment by abellgithub** [comment]
At the current time this value matches the code as the user can't set the density.

**Comment by wonder-sk** [comment]
Right, this was just my misunderstanding - I can see now that the span=128 is hardcoded in the source code too:
https://github.com/hobu/untwine/blob/main/bu/VoxelInfo.hpp#L60
