### ISSUE TITLE
Metadata issues

### ISSUE THREAD

**Issue by connormanning** [hobu/untwine#27]
- Bounds are being written with scientific notation and are losing precision while doing so:
```
"bounds": [1.70148e+06, 3.1115e+06, 1.301, 1.70279e+06, 3.11281e+06, 1308.99],
"boundsConforming": [1.70148e+06, 3.1115e+06, 1.301, 1.70253e+06, 3.11281e+06, 39.281],
```
The actual `boundsConforming` is actually slightly *bigger* than the above since we've rounded 1 digit in X and Y.  Y min in this dataset, for example, is actually `3111499.7`, which is outside of the advertised conforming bounds.

Scientific notation may be technically valid (if the precision loss were to be fixed) but we should just output normal decimal notation anyway.

- Schema for LAZ encoded output isn't correct - the type/size should represent the on-disk storage which is a signed 32-bit int, but it's currently listed as a double.
- Schema attributes are also being reordered from their input:
```
"schema": [
	{"name": "Blue", "type": "unsigned", "size": 2 },
	{"name": "Green", "type": "unsigned", "size": 2 },
	{"name": "Red", "type": "unsigned", "size": 2 },
	{"name": "GpsTime", "type": "float", "size": 8 },
	{"name": "PointSourceId", "type": "unsigned", "size": 2 },
	{"name": "UserData", "type": "unsigned", "size": 1 },
	{"name": "ScanAngleRank", "type": "float", "size": 4 },
	{"name": "ReturnNumber", "type": "unsigned", "size": 1 },
	{"name": "EdgeOfFlightLine", "type": "unsigned", "size": 1 },
	{"name": "NumberOfReturns", "type": "unsigned", "size": 1 },
	{"name": "Z", "type": "float", "scale": 0.01, "offset": 0, "size": 8 },
	{"name": "Classification", "type": "unsigned", "size": 1 },
	{"name": "ScanDirectionFlag", "type": "unsigned", "size": 1 },
	{"name": "Intensity", "type": "unsigned", "size": 2 },
	{"name": "Y", "type": "float", "scale": 0.01, "offset": 0, "size": 8 },
	{"name": "X", "type": "float", "scale": 0.01, "offset": 0, "size": 8 }
],
```

**Comment by abellgithub** [comment]
I don't disagree, but with LAS/LAZ the schema is moot, as it's described by the file format.  Perhaps rather than trying to describe the schema in the LAS/LAZ case, it should just be omitted. Having two schemas is just asking for trouble.

**Comment by connormanning** [comment]
Agreed that it's wonky since we need to duplicate this info throughout LAZ headers for the LAZ encoding, but this metadata is still important even if it also exists in the headers.  XYZ scale for precision information, the list of attributes present, etc.
