### ISSUE TITLE
Unable to convert scaled value to int32

### ISSUE THREAD

**Issue by wonder-sk** [hobu/untwine#46]
Trying to load a file from Helsinki dataset:
https://kartta.hel.fi/helshares/Laserkeilausaineistot/Pintamalli/2017_LAZ/rgb_673496c.laz
(~72 MB)

Untwine fails with the following error:
```
writers.las: Unable to convert scaled value (2549659868) to int32 for dimension 'X' when writing LAS/LAZ file /home/martin/tmp/las/fi-helsinki/ept_rgb_673496c/ept-data/4-2-2-2.laz.
```

The source metadata say:
```
    "minx":     25496500,
    "maxx":     25497000,
    "offset_x": 25000000,
    "scale_x":  0.001,
```

Is this the same issue as #28 ?

**Comment by abellgithub** [comment]
Fixed with 2a5970bf562119f076c8525f7b05d381c0f89ab4
