### ISSUE TITLE
Reporting of errors through API

### ISSUE THREAD

**Issue by wonder-sk** [hobu/untwine#54]
When people try to index a file in QGIS and untwine fails, the untwine sub-process reports `untwine fatal error: XXX` message on its standard error stream before it exists, but untwine API currently does not provide a way for QGIS to actually catch this error message and report it to users.

It would be great to have this possibility, so that QGIS can report these error to users, and they know what went wrong...

**Comment by abellgithub** [comment]
Do you have a suggestion on the API?

**Comment by wonder-sk** [comment]
It could be a new function in `QgisUntwine` class:
```
    std::string errorMessage() const;
```
which could be evaluated once running() returns false, and it would be either empty (success) or non-empty and QGIS would report that error message to user.

**Comment by abellgithub** [comment]
I have this complete, but I wanted to check one thing...

Untwine communicates with QGIS through a pipe. I changed the protocol of the pipe to support the new error message handling. As long as the API code you link into QGIS matches Untwine, all is fine. If you're concerned that some rogue copy of Untwine would get used with QGIS (leading to a protocol mismatch), then maybe we should do something to make sure that versions match. I'd rather not do that, but it could be done.

**Comment by wonder-sk** [comment]
> Untwine communicates with QGIS through a pipe. I changed the protocol of the pipe to support the new error message handling. As long as the API code you link into QGIS matches Untwine, all is fine. If you're concerned that some rogue copy of Untwine would get used with QGIS (leading to a protocol mismatch), then maybe we should do something to make sure that versions match. I'd rather not do that, but it could be done.

I think we don't need to worry about mismatch of qgis/untwine versions - QGIS always has its internal untwine copy which is guaranteed to be compatible with the current QGIS code that calls it, so this should never be an issue...

**Comment by abellgithub** [comment]
That's what I hoped. Thanks!

**Comment by abellgithub** [comment]
Fixed with https://github.com/hobu/untwine/pull/101
