### ISSUE TITLE
C++17 compatibility

### ISSUE THREAD

**Issue by PeterPetrik** [hobu/untwine#55]
Looks like untwine/pdal uses some C++ deprecated in C++17. see https://qgis.org/downloads/macos/nightly/qgis_nightly_master_20210225_122837.log

using C++14 or C++11 is OK see https://github.com/qgis/QGIS/pull/41872

**Comment by abellgithub** [comment]
I don't think this is correct. The errors you're getting are what you'd expect without requiring _at least_ C++11. Looking at the compile line you show, there is no C++ standard mentioned at all. I don't see something like '-std=C++17'

**Comment by PeterPetrik** [comment]
sorry for confusion, looks like the c++xx is not set to this executable https://github.com/qgis/QGIS/blob/96fd952a7b06f2f0cff0e12208e4242cc085ea58/src/providers/pdal/CMakeLists.txt#L104
