### ISSUE TITLE
Running the following command resulted in fatal error

### ISSUE THREAD

**Issue by arknoll** [hobu/untwine#60]
./untwine --files=/home/rock/largetest/merged.laz --output_dir=/home/rock/largetest/ept
untwine fatal error: writers.las: Unable to convert scaled value (-6148407741) to int32 for dimension 'Z' when writing LAS/LAZ file /home/rock/largetest/ept/ept-data/9-380-42-42.laz.

**Comment by abellgithub** [comment]
Assume this is a dup of #53 which is a dup of #46. Let me know if you're using PDAL 2.3 and still have this problem.

**Comment by arknoll** [comment]
ah. will upgrade and test.

**Comment by abellgithub** [comment]
Rewriting your file without crazy scale factors should also fix things.
