### ISSUE TITLE
Fatal error: Unable to fetch data and convert as requested

### ISSUE THREAD

**Issue by wonder-sk** [hobu/untwine#75]
Untwine fails to convert a sample LAZ dataset from Vienna mobile mapping, with the following error thrown towards the end of processing of the input file:
```
Unable to fetch data and convert as requested: ScanAngleRank:float(127.788) -> signed char
```

Test data: https://www.wien.gv.at/gogv/l9ogdkappazunderdatenpaket (5 GB download (!)). Inside the ZIP, in `Scan-Punktwolken/Trajektorie_17134/` there is `Sensor_11004.zip` which contains four LAZ files, all of them end up with this fatal error in Untwine.

Checked with CloudCompare and it was happy to load and display the files.

**Comment by abellgithub** [comment]
What version of PDAL is untwine linked with?

**Comment by wonder-sk** [comment]
I have tested with PDAL 2.0.1

Now checked also with entwine compiled against PDAL 2.2.0, and it also throws the exception.

Will try also with PDAL 2.3...

**Comment by wonder-sk** [comment]
Just tested with untwine from latest `main` and PDAL 2.3 and getting the same error as before.

**Comment by abellgithub** [comment]
OK. Thanks. I'll test here.

**Comment by abellgithub** [comment]
Can you post one file that causes the error?

**Comment by wonder-sk** [comment]
Here's one of the files (115 MB): https://drive.google.com/file/d/1vKrV4uVzew7ozMmTFSNM5u5nSJ7zRZNv/view

**Comment by abellgithub** [comment]
Thanks!

**Comment by abellgithub** [comment]
In their infinite wisdom, the creators of the LAS format changed the notion of scan angle when they created LAS version 1.4. It used to have a range of [-90,90]. They changed it to [-180,180]. Your source file is PDRF 7, which is a 1.4 point format and supports this extended range. The current Untwine implementation *always* creates PDRF 3, which is a pre-1.4 format. The error is simply an acknowledgement of the fact that you can't stick a source value of 132.27 into a range [-90,90].

We are working on a more flexible output scheme that will support output of 1.4 file types that will address this problem. I'm sure something temporary can be done if you think that's necessary. If so, we should discuss what would be acceptable. I doubt many people using QGIS to view point clouds care about scan angle.

**Comment by wonder-sk** [comment]
Ouch. This is a kind of technical detail that ordinary users should not need to worry about and it would be great if Untwine could handle that automatically. Would it make sense to modify Untwine so that it would create the same PDRF type as the source file? If the input files would not have the same PDRF type, Untwine could simply abort, as that should be quite rare. Or is there any problem with that approach? I guess now if laz-perf supports LAS version 1.4, clients such as QGIS should not have a problem to read the newer version too...

For the time being, can you think of some temporary workaround for users? E.g. use PDAL's `filters.assign` to rewrite the file so that scan angle stays in [-90,90] range?

**Comment by abellgithub** [comment]
Users can modify their data such that the scan angle is in range, but that's a hassle.

I can fix this by making it smarter, but I'm just busy right now.

**Comment by abellgithub** [comment]
If you want a quick fix, I can simply clamp the values internally. That would take no time to do and things shouldn't crash.

**Comment by wonder-sk** [comment]
Clamping values would be nice if that doesn't take too much of your time.

I have posted a workaround in https://github.com/qgis/QGIS/issues/45307#issuecomment-930212718 in case people don't want to wait for a proper fix.

**Comment by abellgithub** [comment]
OK. I'll do that since it's trivial, but I'll keep this open until things are really fixed.

**Comment by abellgithub** [comment]
Not trivial. I'll have to think what we should do. :(
