### ISSUE TITLE
Untwine crashes with "No type found for undefined dimension."

### ISSUE THREAD

**Issue by wonder-sk** [hobu/untwine#93]
In a ticket reported in QGIS (https://github.com/qgis/QGIS/issues/45903), the attached LAS file (2.6 MB) fails to get indexes by untwine:
https://drive.google.com/file/d/1LkY08eGLXjvBrV4eR-UzDVQz2hL_kufS/view?usp=sharing

The only output I can see from untwine shipped with QGIS is:
```
Critical: Caught unhandled std::exception:  std::bad_alloc
```

Also tried untwine from recent main branch, that one fails like this:
```
terminate called after throwing an instance of 'pdal::pdal_error'
  what():  No type found for undefined dimension.
```

CloudCompare opens the file without problems, so I guess the file is not corrupted.

**Comment by wonder-sk** [comment]
The same error message is reported with this input file:
https://sitn.ne.ch/web/diffusion/lidar/qgis/lidar_aerial_2016_locle_2547500_1212000.laz

**Comment by abellgithub** [comment]
I've tried Unwitne with both of these files and had no issues. I used the command:

```untwine -i <filename> -o test.ept```

I also tried using version 2.0 of PDAL and still had no issues. Can you provide any more detail? Does the above command work for you?

**Comment by abellgithub** [comment]
It would help if I had a stack trace of the error.

**Comment by wonder-sk** [comment]
Hmm now after updating to untwine's latest main (6421a7fadc) and laz-perf 3.0.0, using PDAL 2.0.1 from ubuntu 20.04 packages, I get the following error:
```
untwine fatal error: writers.las: Can't write LAZ output. PDAL not built with LAZperf.
```
... even with files that used to work before. Does addition of COPC support in Untwine mean that LAZperf is now strictly required even if COPC is not being written? Ubuntu 20.04 packages of PDAL use laszip (3.4.3), not lazperf

**Comment by hobu** [comment]
> Does addition of COPC support in Untwine mean that LAZperf is now strictly required

Yes. And for PDAL 2.4.0, we will be dropping LASzip support as well, but in exchange for the consternation this will cause, I am hoping to complete a relicensing of LASzip to Apache Public Licensing after the new year that will allow vendoring of laz-perf directly into PDAL.

**Comment by abellgithub** [comment]
Hmm. Did we put something in for this already? I don't recall it, but I forget stuff.

**Comment by wonder-sk** [comment]
After upgrading to PDAL master + laz-perf 3.0 + untwine main, both files work for me as well... so the problem was probably fixed in newer pdal or untwine.
