### ISSUE TITLE
--clean_temp_dir doesn't seem to work for --single_file

### ISSUE THREAD

**Issue by hobu** [hobu/untwine#97]

**Comment by abellgithub** [comment]
Looking at the code I don't see how this would be the case. Do you have some example?

**Comment by abellgithub** [comment]
I think I've figured this out. `--clean_temp_dir` is a boolean value and is *true* by default. When you specify the argument without an explicit value (`true` or `false`), it inverts the default value. So if you say `untwine ... --clean_temp_dir`, you're saying to *not* clean the temp directory.

I think this is confusing, so I'm going to ditch this option in favor of
`--preserve_temp_dir` with a default of false.

**Comment by abellgithub** [comment]
Bottom line... in order to get the behavior you were wanting, don't mess with the option.

**Comment by abellgithub** [comment]
Fixed by #110
